# Generated code do not commit.
file(TO_CMAKE_PATH "/home/student/develop/flutter" FLUTTER_ROOT)
file(TO_CMAKE_PATH "/home/student/VartChat" PROJECT_DIR)

set(FLUTTER_VERSION "0.4.8+11" PARENT_SCOPE)
set(FLUTTER_VERSION_MAJOR 0 PARENT_SCOPE)
set(FLUTTER_VERSION_MINOR 4 PARENT_SCOPE)
set(FLUTTER_VERSION_PATCH 8 PARENT_SCOPE)
set(FLUTTER_VERSION_BUILD 11 PARENT_SCOPE)

# Environment variables to pass to tool_backend.sh
list(APPEND FLUTTER_TOOL_ENVIRONMENT
  "FLUTTER_ROOT=/home/student/develop/flutter"
  "PROJECT_DIR=/home/student/VartChat"
  "DART_DEFINES=RkxVVFRFUl9CVUlMRF9OQU1FPTAuNC44,RkxVVFRFUl9CVUlMRF9OVU1CRVI9MTE=,RkxVVFRFUl9WRVJTSU9OPTMuNDcuNg==,RkxVVFRFUl9DSEFOTkVMPXN0YWJsZQ==,RkxVVFRFUl9HSVRfVVJMPWh0dHBzOi8vZ2l0aHViLmNvbS9mbHV0dGVyL2ZsdXR0ZXIuZ2l0,RkxVVFRFUl9GUkFNRVdPUktfUkVWSVNJT049NWZjMzQ2ODM5Yg==,RkxVVFRFUl9FTkdJTkVfUkVWSVNJT049NjkyMTM2Y2I2NQ==,RkxVVFRFUl9EQVJUX1ZFUlNJT049My4xMy41"
  "DART_OBFUSCATION=false"
  "TRACK_WIDGET_CREATION=true"
  "TREE_SHAKE_ICONS=true"
  "PACKAGE_CONFIG=/home/student/VartChat/.dart_tool/package_config.json"
  "FLUTTER_TARGET=lib/main.dart"
)
