// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVumiP_ZwzULsilZWD1ZeiCLhfUTe6GgE',
    appId: '1:209021739249:web:202c8fd6e0f31cc6bb8950',
    messagingSenderId: '209021739249',
    projectId: 'vartchat-2b256',
    authDomain: 'vartchat-2b256.firebaseapp.com',
    storageBucket: 'vartchat-2b256.firebasestorage.app',
    measurementId: 'G-L7R12HZFML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA2wbbF6JGkKA-MmY-NbMATW8CxwE-T7I',
    appId: '1:209021739249:android:c114455ab6f1f6b2bb8950',
    messagingSenderId: '209021739249',
    projectId: 'vartchat-2b256',
    storageBucket: 'vartchat-2b256.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh8YvyZ_BjbXib9EUB0sQfDvvOD1QfnK8',
    appId: '1:209021739249:ios:305d1a065ce86681bb8950',
    messagingSenderId: '209021739249',
    projectId: 'vartchat-2b256',
    storageBucket: 'vartchat-2b256.firebasestorage.app',
    iosBundleId: 'com.vartrusdata.vartchat.vartchat',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh8YvyZ_BjbXib9EUB0sQfDvvOD1QfnK8',
    appId: '1:209021739249:ios:305d1a065ce86681bb8950',
    messagingSenderId: '209021739249',
    projectId: 'vartchat-2b256',
    storageBucket: 'vartchat-2b256.firebasestorage.app',
    iosBundleId: 'com.vartrusdata.vartchat.vartchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVumiP_ZwzULsilZWD1ZeiCLhfUTe6GgE',
    appId: '1:209021739249:web:e55823e8c8c6b0a5bb8950',
    messagingSenderId: '209021739249',
    projectId: 'vartchat-2b256',
    authDomain: 'vartchat-2b256.firebaseapp.com',
    storageBucket: 'vartchat-2b256.firebasestorage.app',
    measurementId: 'G-NHH1DHMX09',
  );
}
